db:
  mongo_uri: "mongodb://search-mongo:27017"
  database: "search"
  collection: "documents"

redis:
  host: "search-redis"
  port: 6379
  db: 0
  redis_url: "redis://search-redis:6379/0"

logic:
  download_delay: 2.0
  concurrent_requests_per_domain: 1
  reindex_after_days: 7

sitemaps:
  - "https://www.championat.com/sitemap/news/631.xml"
  - "https://www.championat.com/sitemap/news/632.xml"
  - "https://www.championat.com/sitemap/news/633.xml"
  - "https://www.sport-express.ru/sitemap/news/2026-2-1.xml"
  - "https://www.sport-express.ru/sitemap/news/2026-1-4.xml"
  - "https://www.sport-express.ru/sitemap/news/2026-1-3.xml"
  - "https://www.sport-express.ru/sitemap/news/2026-1-2.xml"
  - "https://www.sport-express.ru/sitemap/news/2026-1-1.xml"
  - "https://www.sport-express.ru/sitemap/news/2025-12-3.xml"
  - "https://www.sport-express.ru/sitemap/news/2025-12-2.xml"
  - "https://www.sport-express.ru/sitemap/news/2025-12-1.xml"
  - "https://www.sport-express.ru/sitemap/news/2025-11-4.xml"
  - "https://www.sovsport.ru/sitemap-articles.xml"
  - "https://www.sovsport.ru/sitemap-news.xml"


